# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V${project.version}
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config file for commands and messages, place holders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# ------------------------------------------
# Don't change the config version!

Config Version: 2

# Different branches recieve different updates, Spigot uses the latest update from Spigot. Nightly uses the latest build from my CI server which may include bugs.
Update Branch: Spigot

# Checks if an update is available and notifies staff, uses Spigot
Update Checks: true

# If true the server will download and install an update when it becomes avaliable
Auto Update: true

# ITEMNAME-DATA:AMOUNT:ENCHANTMENTS|SEPARATED|BY|PIPE|WITH|LEVELS|LIKE|THIS-3
# Commands can be like COMMAND:give %name% 100 coins
# Item name must be a Bukkit material, list here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/material/package-summary.html
Crates:
  Common:
    Items:
    - IRON_SWORD:1:DAMAGE_ALL-3
    - COOKED_BEEF:32:DAMAGE_ALL-100
    - WOOL-5
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
  Rare:
    Items:
    - DIAMOND_SWORD:1:DAMAGE_ALL
    - COMMAND:say %name% This is all you won... enjoy!
    Knockback: 1.0
    Broadcast: false
    Firework: false
    Color: GOLD
  Ultra:
    Items:
    - DIAMOND_SWORD:1:DAMAGE_ALL-3
    Knockback: 2.0
    Broadcast: true
    Firework: true
    Color: DARK_PURPLE
  Vote:
    Items:
    - GOLD_SWORD:1:DAMAGE_ALL-5
    Knockback: 10.0
    Broadcast: false
    Firework: true
    Color: YELLOW

# Modify different options of the crate key
Crate Keys:
  Item: TRIPWIRE_HOOK
  Name: "%type% Crate Key!"
  Enchantments:
  - DAMAGE_ALL

# If true the plugin will use the interact event instead of the inventory open event
Use Interact: false

# If true knockback will not happen and a GUI will open with what items can be won
Crate Previews: false

# If true when the player claims a crate a GUI will open with the winning item in (not yet done)
Crate Open GUI: false

# If true it will stop players without the admin perm breaking crates
Crate Protection: false

# Below are all messages that can be edited in the plugin
Messages:
  Prefix: "&7[&bCratesPlus&7]"
  Command No Permission: "&cYou do not have the correct permission to run this command"
  Crate Open Without Key: "&cYou must be holding a %crate% &ckey to open this crate"
  Key Given: "&aYou have been given a %crate% &acrate key"
  Broadcast: "&d%displayname% &dopened a %crate% &dcrate"
  Cant Place: "&cYou can not place crate keys"