# [][][][][][][][][][][][][][][][][][][][][]
#  BackupManager V${project.version}
# [][][][][][][][][][][][][][][][][][][][][]

Update Checks: true
Auto Update: true
Update Branch: nightly

Advanced Logs: false
Backup Location: "backups"
Backup On:
  Server Start: true
  Every 15 Minutes: true