# [][][][][][][][][][][][][][][][][][][][][]
#  BackupManager V${project.version}
# [][][][][][][][][][][][][][][][][][][][][]

Advanced Logs: false
Backup Location: "backups"
Backup On:
  Server Start: true
  Every 15 Minutes: true
FTP Backup:
  Enabled: false
  FTP Host: 127.0.0.1
  FTP User: username
  FTP Pass: password
  FTP Port: 21